//
//  Website.swift
//  AnimalScan
//
//  Created by Jules Liegeois on 04/06/2026.
//

import SwiftUI

struct Article: Identifiable {
    var id = UUID()
    var image: String
    var title: String
    var subTitle: String
    var content: String
    var content2: String
    var content3: String
}

var articles = [
    Article(image: "cnard2", title: "Est-ce que les canards volent ?", subTitle: "Canards sauvages : Maîtres du ciel", content: "Cat ipsum dolor sit amet, terrorize the hundred-and-twenty-pound rottweiler and steal his bed, not sorry. Play with twist ties open the door, let me out, let me out, let me-out, let me-aow, let meaow, meaow! for dream about hunting birds throw down all the stuff in the kitchen sleep.", content2: "Hate dogs pee in the shoe or kitty time. Swipe at owner's legs meowsiers and your pillow is now my pet bed. Milk the cow i like big cats and i can not lie but instantly break out into full speed gallop across the house for no reason for ooooh feather moving feather!.", content3: "Paw at your fat belly cat milk copy park pee walk owner escape bored tired cage droppings sick vet vomit i show my fluffy belly but it's a trap! if you pet it i will tear up your hand for prance along on top of the garden fence, annoy the neighbor's dog and make it bark. I want to go outside let me go outside nevermind inside is better mess up all the toilet paper the fat cat sat on the mat bat away with paws. There's a forty year old lady there let us feast sleep on dog bed, force dog to sleep on floor yet stare at guinea pigs don't nosh on the birds. Human is in bath tub, emergency! drowning! meooowww! bleghbleghvomit my furball really tie the room together."),
    Article(image: "quizz1", title: "Across the house for no reason", subTitle: "Canards sauvages : Maîtres du ciel", content: "Cat ipsum dolor sit amet, terrorize the hundred-and-twenty-pound rottweiler and steal his bed, not sorry. Play with twist ties open the door, let me out, let me out, let me-out, let me-aow, let meaow, meaow! for dream about hunting birds throw down all the stuff in the kitchen sleep.", content2: "Hate dogs pee in the shoe or kitty time. Swipe at owner's legs meowsiers and your pillow is now my pet bed. Milk the cow i like big cats and i can not lie but instantly break out into full speed gallop across the house for no reason for ooooh feather moving feather!.", content3: "Paw at your fat belly cat milk copy park pee walk owner escape bored tired cage droppings sick vet vomit i show my fluffy belly but it's a trap! if you pet it i will tear up your hand for prance along on top of the garden fence, annoy the neighbor's dog and make it bark. I want to go outside let me go outside nevermind inside is better mess up all the toilet paper the fat cat sat on the mat bat away with paws. There's a forty year old lady there let us feast sleep on dog bed, force dog to sleep on floor yet stare at guinea pigs don't nosh on the birds. Human is in bath tub, emergency! drowning! meooowww! bleghbleghvomit my furball really tie the room together."),
    Article(image: "quizz2", title: "All the stuff in the kitchen sleep.", subTitle: "Canards sauvages : Maîtres du ciel", content: "Cat ipsum dolor sit amet, terrorize the hundred-and-twenty-pound rottweiler and steal his bed, not sorry. Play with twist ties open the door, let me out, let me out, let me-out, let me-aow, let meaow, meaow! for dream about hunting birds throw down all the stuff in the kitchen sleep.", content2: "Hate dogs pee in the shoe or kitty time. Swipe at owner's legs meowsiers and your pillow is now my pet bed. Milk the cow i like big cats and i can not lie but instantly break out into full speed gallop across the house for no reason for ooooh feather moving feather!.", content3: "Paw at your fat belly cat milk copy park pee walk owner escape bored tired cage droppings sick vet vomit i show my fluffy belly but it's a trap! if you pet it i will tear up your hand for prance along on top of the garden fence, annoy the neighbor's dog and make it bark. I want to go outside let me go outside nevermind inside is better mess up all the toilet paper the fat cat sat on the mat bat away with paws. There's a forty year old lady there let us feast sleep on dog bed, force dog to sleep on floor yet stare at guinea pigs don't nosh on the birds. Human is in bath tub, emergency! drowning! meooowww! bleghbleghvomit my furball really tie the room together."),
    Article(image: "quizz3", title: "Hate dogs pee in the shoe or", subTitle: "Canards sauvages : Maîtres du ciel", content: "Cat ipsum dolor sit amet, terrorize the hundred-and-twenty-pound rottweiler and steal his bed, not sorry. Play with twist ties open the door, let me out, let me out, let me-out, let me-aow, let meaow, meaow! for dream about hunting birds throw down all the stuff in the kitchen sleep.", content2: "Hate dogs pee in the shoe or kitty time. Swipe at owner's legs meowsiers and your pillow is now my pet bed. Milk the cow i like big cats and i can not lie but instantly break out into full speed gallop across the house for no reason for ooooh feather moving feather!.", content3: "Paw at your fat belly cat milk copy park pee walk owner escape bored tired cage droppings sick vet vomit i show my fluffy belly but it's a trap! if you pet it i will tear up your hand for prance along on top of the garden fence, annoy the neighbor's dog and make it bark. I want to go outside let me go outside nevermind inside is better mess up all the toilet paper the fat cat sat on the mat bat away with paws. There's a forty year old lady there let us feast sleep on dog bed, force dog to sleep on floor yet stare at guinea pigs don't nosh on the birds. Human is in bath tub, emergency! drowning! meooowww! bleghbleghvomit my furball really tie the room together."),
    Article(image: "quizz4", title: "I show my fluffy belly", subTitle: "Canards sauvages : Maîtres du ciel", content: "Cat ipsum dolor sit amet, terrorize the hundred-and-twenty-pound rottweiler and steal his bed, not sorry. Play with twist ties open the door, let me out, let me out, let me-out, let me-aow, let meaow, meaow! for dream about hunting birds throw down all the stuff in the kitchen sleep.", content2: "Hate dogs pee in the shoe or kitty time. Swipe at owner's legs meowsiers and your pillow is now my pet bed. Milk the cow i like big cats and i can not lie but instantly break out into full speed gallop across the house for no reason for ooooh feather moving feather!.", content3: "Paw at your fat belly cat milk copy park pee walk owner escape bored tired cage droppings sick vet vomit i show my fluffy belly but it's a trap! if you pet it i will tear up your hand for prance along on top of the garden fence, annoy the neighbor's dog and make it bark. I want to go outside let me go outside nevermind inside is better mess up all the toilet paper the fat cat sat on the mat bat away with paws. There's a forty year old lady there let us feast sleep on dog bed, force dog to sleep on floor yet stare at guinea pigs don't nosh on the birds. Human is in bath tub, emergency! drowning! meooowww! bleghbleghvomit my furball really tie the room together.")
]


